language: node_js
node_js: lts/dubnium
services: 
  - docker
addons:
  apt:
    packages:
    - libsecret-1-0
script:
  - chmod +x ./scripts/docker-deploy.sh
deploy:
  - provider: npm
    api_key:
      secure: dfeuYQQxLdQ+qAedk77661N3kX0zqQxKmgEEGeHSPphZllk2ctnDD0j22ZmgI3EDJTri6wnGFbu4oFHNWEptpdYqI4D24UpQ+cx1ASMogtH2+yTFTVmkkMOSkOwwxE+O7kHQfZNA8gJ1GGB29289iVNoIpYc+JKFpYS5mfKYx6rn4dK7ENtA8gwn083/vLmtnWOmEiKhSVWAie7SF4j+fetTcz3kCV1V5JyE1NzJ8lkZ13g2NgHfssCuEQDTeiXIwGhVJ/sIVs5l6fYsFsmY+6Ozm+Giwe0fbp4MAZf/QvqeeSQmeuvuUnyKk/CaeU3VnjAgigf3ux2US07Bt3k2ZOoPJe6WcqMGqKNrhtEBdtIw6le2+mRc8p7Pft6p7w0kzQV3+k/sFe3nd7XOIJqwj0CfNxyAVFlFPjd54T7O4U9qtrvXt8HJicXu/hmQn2HKPtsm2P2kURXUyMHLkW2G7Q/1bip3iEO5n7IElR1J4iyj64ZZJJZ/WW1ysslU+5rFGS7qGmk0DaRD/2ZpSzbjarKDM1OWeffwkS8XujPWNi1Oa6nnCmm2cAVOWpUu1cMgz9LAd/0irRHHFRICHRuqnko4mzkWZxy7PkfaIy/Aslr0tUFHxBY7ZHxdrxuWf8iMOXJ6/hEmu03O1Ru1Eq2ea3FxQ6RK3Zrq34IQ9qUOVXc=
    on:
      tags: true
      repo: MankMantos/manktwine
    email:
      secure: fjtzQ+SuJItUHnal/9foPABn3AbMUk4prFqKCoTusDCSe1+HyAUj/WgsaYwoxwmd2e6Wj1s3xA+m5JLje8PXg/PLbdkMd9sSraMmsZGgoPxa7rcAi0BQNYQtiZwz7ldf8tv7KQLbEdlQWjH6VtkA4KPcA8uchTuTV6YKa0GD8/jXW9fcSpgUJKJjYKCqrunMfOL7/2qMI/0INS+el+MAQzdgDCWpD/Hrgk1wSiPzvCj03vug/AV+UJwe4rahUKOoFh51/L3ewDC/K6CPonQ+8WrDGnyc90SIOo72JFKHJd4vstJb/Apu2RBVULEUc7sjxrRsSKN9GpkiCp7DJ6ctXnAnkJJCPgFnJmTRspeLowRxJx1hWnat8dWJgzP2ngDYAOF2hLD/f3U9/SADrYT3htLws5KrPRD7xSqsRraiVwWxkPewiu+K6DjoGq8IoPmpewvmqOkxVoOhQJcbNd0jemQipELpEq7Nptiddq+di9qRxZk2eOBnYWfDwdnwvtCLksTO1crO0mecE/EatRziazsEqIJO7DplvMEbxZr2Skoz8m7q10GBa4RDSeickUHZzkyX53HaJNr6b7ZTPKt03g42j0G1r6PtKvBk/ZwsnnNQqJfyro1Z5fHZ7tbLD0M3sYhoSJL5HASKcXgs8tc47Oljtj/jPzLC0rh385Pnz3Q=
  - provider: script
    script: bash ./scripts/docker-deploy.sh
    skip_cleanup: true
    on:
      tags: true
      repo: MankMantos/manktwine
env:
  global:
  - secure: cg1r0EzP13RfJBlwk0r8anPG0C4eLJzZdctM2rxzGJJB4kNwkd46Dk2TN3boGy54Q5U0chidJLqNcUIMYgyn4frw2oZI2QC2DvL0FgI9Fc3gCC9B/r1b6lWaokCs6OnjA5Dv/lZMRwcr9wQUV9WZlfVo0//koV7APBqZXIqKaJYMj3uFMM2U4mi0Sxt/jrpjCb4etwYobxvjs2ES3UYCLPXNj+HnYKsNHuFmy95VmFOAFLl9cnjdEmoFNcR1WgkuDspEBTrMrJBzdUXsOQxa1dTQKQPL0yi/QPlyquyjEkrR/Ya1pmY8lLMPboNGMx0+7k0ygdYKUFsuydBEhAdvZaUpaWOY22ZY9a7Ekz1qxEcexu+tdzyiUbZQMcBdtZhxUumfHhu/3iXM56onB67TCQVLR6DgzFfMzTVq4/a6vh3T0ITxDl1jg4MHlsP7eiFAQ5j0EEkM9A+5NXNuGRV/9fRCJdNuyaep+skzkqMh6C3B194N0GOsiu030Pm/wm4NtpVnQV5ETkRwiIgH+ksWKWhT0xT1GURXbsHfKlPJTmtvqidvhuCuZ5PL0WQNvtKyFa8eaR1/XW6zKXBdQqdeyNs+eIFIiHANrwzwHJnIPA2UMg46AyVZJ6BxHoLrkgSOOxV2JSdfGc2K/9wE17IF7oV8EghXpyx0DltB98y/Kmg=
  - secure: gMDzgTz8CYegD+SsW6krGNA+QWVTH5JCAi5UY7adilVorbCAbTqm6+/spxNLXASv2E2pnRTorG6duUoXNqZhZErdK607IXpWJIT5m+EEssAQHjyhQwQvb1UjvQ/es4LNgZXhn3pWl4NiSBhshTN08qNDJlOHvVEv5bFJA6dj7cjBZYTb1kKhcevdSgQ0Fz56Fmg+itYPhzVElaLOFzZcVb9jmtJBiJq15An0HzmCF/CdJ9g0DG77Laxe9voFnKxAjpebjSy/S1RsP5UdDntbaeHhQmAWv1QHUIBgNkME87dv3t0ms85SkcRkq/g5zIZFr3C2reOxHFBaE1fZojcaRxuqx8fUslErriq3ynuC8rN1Pc4qBLcEp3oD9410ROeaPR82ZaAp+bkenBJRfxIdKNAkSHLAky/qVop8ML9ls8i+2LJ0VQROngUmO3/0SmmvU9xG4hroxyastVGeDd0P8BTH2r9OJhBsNwHdJnIYEQ9vVKMnWYiytU3dQHAeh13kJinY0Lsgnw5zAlNSuwDUh62sz0oV5YDAeHtyxmXbeBDYfIudYgHcL7NFHPVcqUDhF33ttY2w+fcsTUxbqjnkgp+eMllCswBipkDrrT8qcVFDy4R2C0yh8Ykrfq27EOvMYYe50PyS0lXCFv9+O0gJyxfw2HSbESd1S/oeCulT/qA=
